### PR TITLE
Add compression to LineProtocolClient

### PR DESCRIPTION
**Pull request by stmax82**
I added gzip compression to HTTP POST requests.

Quick tests have shown that it reduces Content-Length down to 50% (for short single point requests) and down to <10% (for large multi-point requests).

Compression can be enabled using an optional parameter of the LineProtocolClient constructor.
Default is off so the behavior should be the same as before.

### CODE REVIEW

**Comment by stmax82** [comment]
@bednar @nblumhardt could we get updates for the open pull requests please?

**Comment by nblumhardt** [comment]
@stmax82 I'm no longer a maintainer, here, sorry.

**Review by bednar — CHANGES_REQUESTED** [review]
Hi @stmax82,

thanks for your PR.

Could you please  update `CHANGELOG.md` and add unit tests to cover your changes?

Regards

**Comment by stmax82** [comment]
Hi @bednar,

> Could you please update `CHANGELOG.md` and add unit tests to cover your changes?

done - I updated the changelog and added a few tests for the LineProtocolClient with and without compression.

**Review by bednar — APPROVED** [review]
LGTM

**Comment by bednar** [comment]
Hi @stmax82 ,

The issue is fixed in [1.2.0 milestone](https://github.com/influxdata/influxdb-csharp/milestone/2). 


If you would like to use a preview version use our nightly build: [InfluxDB.LineProtocol 1.2.0-dev-00018](https://www.nuget.org/packages/InfluxDB.LineProtocol/1.2.0-dev-00018).

Regards

**Pull request merged**
