### PR TITLE
#7 Added overload for timestamp

### PR DESCRIPTION
**Pull request by HakanL**

### CODE REVIEW

**Comment by nblumhardt** [comment]
Thanks, looks good.

Instead of an overload, given the current shape of the API, what do you think of:

```csharp
public void Write(string measurement, DateTime timestamp, IReadOnlyDictionary<string, object> fields, IReadOnlyDictionary<string, string> tags = null, DateTime? timestamp = null)
```

?

Just a bit more consistent with the way the other methods are laid out...

**Comment by HakanL** [comment]
I think that's fine/better, I just didn't want to change your existing API

**Comment by HakanL** [comment]
Although adding it to the end isn't breaking anything :)

**Comment by HakanL** [comment]
Changed, please re-verify.

**Comment by nblumhardt** [comment]
Beautiful, much appreciated!

Nick

**Pull request merged**
